# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appesi', '0006_auto_20171030_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoramod',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
